name: Claim Genshin Daily Rewards
on:   
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  
jobs:
  claim-rewards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node.js
      uses: actions/setup-node@v4
      with: 
        node-version: 20
    - name: Install dependencies
      run: npm install
      
    - name: Run Scipt
      run: npm run script